//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.14 at 04:04:07 AM EST 
//


package org.proteomecommons.io.dataxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Component complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Component">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cvParam" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}CVParam" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="userParam" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}UserParam" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="paramGroupRef" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}ParamGroupRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="source" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}Source" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="analyzer" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}Analyzer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="detector" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}Detector" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="software" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}Software" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Component", propOrder = {
    "cvParam",
    "userParam",
    "paramGroupRef",
    "source",
    "analyzer",
    "detector",
    "software"
})
public class Component {

    @XmlElement(required = true)
    protected List<CVParam> cvParam;
    @XmlElement(required = true)
    protected List<UserParam> userParam;
    @XmlElement(required = true)
    protected List<ParamGroupRef> paramGroupRef;
    @XmlElement(required = true)
    protected List<Source> source;
    @XmlElement(required = true)
    protected List<Analyzer> analyzer;
    @XmlElement(required = true)
    protected List<Detector> detector;
    @XmlElement(required = true)
    protected List<Software> software;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the cvParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cvParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCvParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CVParam }
     * 
     * 
     */
    public List<CVParam> getCvParam() {
        if (cvParam == null) {
            cvParam = new ArrayList<CVParam>();
        }
        return this.cvParam;
    }

    /**
     * Gets the value of the userParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserParam }
     * 
     * 
     */
    public List<UserParam> getUserParam() {
        if (userParam == null) {
            userParam = new ArrayList<UserParam>();
        }
        return this.userParam;
    }

    /**
     * Gets the value of the paramGroupRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paramGroupRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParamGroupRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamGroupRef }
     * 
     * 
     */
    public List<ParamGroupRef> getParamGroupRef() {
        if (paramGroupRef == null) {
            paramGroupRef = new ArrayList<ParamGroupRef>();
        }
        return this.paramGroupRef;
    }

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Source }
     * 
     * 
     */
    public List<Source> getSource() {
        if (source == null) {
            source = new ArrayList<Source>();
        }
        return this.source;
    }

    /**
     * Gets the value of the analyzer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analyzer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnalyzer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Analyzer }
     * 
     * 
     */
    public List<Analyzer> getAnalyzer() {
        if (analyzer == null) {
            analyzer = new ArrayList<Analyzer>();
        }
        return this.analyzer;
    }

    /**
     * Gets the value of the detector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Detector }
     * 
     * 
     */
    public List<Detector> getDetector() {
        if (detector == null) {
            detector = new ArrayList<Detector>();
        }
        return this.detector;
    }

    /**
     * Gets the value of the software property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the software property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoftware().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Software }
     * 
     * 
     */
    public List<Software> getSoftware() {
        if (software == null) {
            software = new ArrayList<Software>();
        }
        return this.software;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
