//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.14 at 04:04:07 AM EST 
//


package org.proteomecommons.io.dataxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataGroup">
 *   &lt;complexContent>
 *     &lt;extension base="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}ParamGroup">
 *       &lt;sequence>
 *         &lt;element name="delimitedData" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}DelimitedDataArray" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stringData" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}StringDataArray" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="binaryData" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}BinaryDataArray" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="experimentRef" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="sampleRef" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="spectrumRef" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataGroup", propOrder = {
    "delimitedData",
    "stringData",
    "binaryData"
})
public class DataGroup
    extends ParamGroup
{

    @XmlElement(required = true)
    protected List<DelimitedDataArray> delimitedData;
    @XmlElement(required = true)
    protected List<StringDataArray> stringData;
    @XmlElement(required = true)
    protected List<BinaryDataArray> binaryData;
    @XmlAttribute
    protected String experimentRef;
    @XmlAttribute
    protected String sampleRef;
    @XmlAttribute
    protected String spectrumRef;

    /**
     * Gets the value of the delimitedData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delimitedData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelimitedData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DelimitedDataArray }
     * 
     * 
     */
    public List<DelimitedDataArray> getDelimitedData() {
        if (delimitedData == null) {
            delimitedData = new ArrayList<DelimitedDataArray>();
        }
        return this.delimitedData;
    }

    /**
     * Gets the value of the stringData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringDataArray }
     * 
     * 
     */
    public List<StringDataArray> getStringData() {
        if (stringData == null) {
            stringData = new ArrayList<StringDataArray>();
        }
        return this.stringData;
    }

    /**
     * Gets the value of the binaryData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BinaryDataArray }
     * 
     * 
     */
    public List<BinaryDataArray> getBinaryData() {
        if (binaryData == null) {
            binaryData = new ArrayList<BinaryDataArray>();
        }
        return this.binaryData;
    }

    /**
     * Gets the value of the experimentRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExperimentRef() {
        return experimentRef;
    }

    /**
     * Sets the value of the experimentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExperimentRef(String value) {
        this.experimentRef = value;
    }

    /**
     * Gets the value of the sampleRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleRef() {
        return sampleRef;
    }

    /**
     * Sets the value of the sampleRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleRef(String value) {
        this.sampleRef = value;
    }

    /**
     * Gets the value of the spectrumRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpectrumRef() {
        return spectrumRef;
    }

    /**
     * Sets the value of the spectrumRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpectrumRef(String value) {
        this.spectrumRef = value;
    }

}
