//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.14 at 04:04:07 AM EST 
//


package org.proteomecommons.io.dataxml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.proteomecommons.io.dataxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataXML_QNAME = new QName("http://sashimi.sourceforge.net/schema_revision/DataXML_0.1", "dataXML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.proteomecommons.io.dataxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataGroup }
     * 
     */
    public DataGroup createDataGroup() {
        return new DataGroup();
    }

    /**
     * Create an instance of {@link ParamGroupList }
     * 
     */
    public ParamGroupList createParamGroupList() {
        return new ParamGroupList();
    }

    /**
     * Create an instance of {@link SourceFileList }
     * 
     */
    public SourceFileList createSourceFileList() {
        return new SourceFileList();
    }

    /**
     * Create an instance of {@link DelimitedDoubleArray }
     * 
     */
    public DelimitedDoubleArray createDelimitedDoubleArray() {
        return new DelimitedDoubleArray();
    }

    /**
     * Create an instance of {@link InstrumentSetting }
     * 
     */
    public InstrumentSetting createInstrumentSetting() {
        return new InstrumentSetting();
    }

    /**
     * Create an instance of {@link Experiment }
     * 
     */
    public Experiment createExperiment() {
        return new Experiment();
    }

    /**
     * Create an instance of {@link UserParam }
     * 
     */
    public UserParam createUserParam() {
        return new UserParam();
    }

    /**
     * Create an instance of {@link Precursor }
     * 
     */
    public Precursor createPrecursor() {
        return new Precursor();
    }

    /**
     * Create an instance of {@link SpectrumList }
     * 
     */
    public SpectrumList createSpectrumList() {
        return new SpectrumList();
    }

    /**
     * Create an instance of {@link ParamGroup }
     * 
     */
    public ParamGroup createParamGroup() {
        return new ParamGroup();
    }

    /**
     * Create an instance of {@link DataProcessing }
     * 
     */
    public DataProcessing createDataProcessing() {
        return new DataProcessing();
    }

    /**
     * Create an instance of {@link Acquisition }
     * 
     */
    public Acquisition createAcquisition() {
        return new Acquisition();
    }

    /**
     * Create an instance of {@link Spectrum }
     * 
     */
    public Spectrum createSpectrum() {
        return new Spectrum();
    }

    /**
     * Create an instance of {@link DelimitedTimeArray }
     * 
     */
    public DelimitedTimeArray createDelimitedTimeArray() {
        return new DelimitedTimeArray();
    }

    /**
     * Create an instance of {@link Admin }
     * 
     */
    public Admin createAdmin() {
        return new Admin();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Analyzer }
     * 
     */
    public Analyzer createAnalyzer() {
        return new Analyzer();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link DataGroupList }
     * 
     */
    public DataGroupList createDataGroupList() {
        return new DataGroupList();
    }

    /**
     * Create an instance of {@link SpectrumData }
     * 
     */
    public SpectrumData createSpectrumData() {
        return new SpectrumData();
    }

    /**
     * Create an instance of {@link Sample }
     * 
     */
    public Sample createSample() {
        return new Sample();
    }

    /**
     * Create an instance of {@link SampleList }
     * 
     */
    public SampleList createSampleList() {
        return new SampleList();
    }

    /**
     * Create an instance of {@link DelimitedFloatArray }
     * 
     */
    public DelimitedFloatArray createDelimitedFloatArray() {
        return new DelimitedFloatArray();
    }

    /**
     * Create an instance of {@link Detector }
     * 
     */
    public Detector createDetector() {
        return new Detector();
    }

    /**
     * Create an instance of {@link DelimitedBooleanArray }
     * 
     */
    public DelimitedBooleanArray createDelimitedBooleanArray() {
        return new DelimitedBooleanArray();
    }

    /**
     * Create an instance of {@link CVList }
     * 
     */
    public CVList createCVList() {
        return new CVList();
    }

    /**
     * Create an instance of {@link Instrument }
     * 
     */
    public Instrument createInstrument() {
        return new Instrument();
    }

    /**
     * Create an instance of {@link CVParam }
     * 
     */
    public CVParam createCVParam() {
        return new CVParam();
    }

    /**
     * Create an instance of {@link DelimitedIntArray }
     * 
     */
    public DelimitedIntArray createDelimitedIntArray() {
        return new DelimitedIntArray();
    }

    /**
     * Create an instance of {@link AcquisitionList }
     * 
     */
    public AcquisitionList createAcquisitionList() {
        return new AcquisitionList();
    }

    /**
     * Create an instance of {@link SoftwareList }
     * 
     */
    public SoftwareList createSoftwareList() {
        return new SoftwareList();
    }

    /**
     * Create an instance of {@link DataXML }
     * 
     */
    public DataXML createDataXML() {
        return new DataXML();
    }

    /**
     * Create an instance of {@link InstrumentList }
     * 
     */
    public InstrumentList createInstrumentList() {
        return new InstrumentList();
    }

    /**
     * Create an instance of {@link Software }
     * 
     */
    public Software createSoftware() {
        return new Software();
    }

    /**
     * Create an instance of {@link ExperimentList }
     * 
     */
    public ExperimentList createExperimentList() {
        return new ExperimentList();
    }

    /**
     * Create an instance of {@link DataProcessingList }
     * 
     */
    public DataProcessingList createDataProcessingList() {
        return new DataProcessingList();
    }

    /**
     * Create an instance of {@link ParamGroupRef }
     * 
     */
    public ParamGroupRef createParamGroupRef() {
        return new ParamGroupRef();
    }

    /**
     * Create an instance of {@link CV }
     * 
     */
    public CV createCV() {
        return new CV();
    }

    /**
     * Create an instance of {@link BinaryDataArray }
     * 
     */
    public BinaryDataArray createBinaryDataArray() {
        return new BinaryDataArray();
    }

    /**
     * Create an instance of {@link PrecursorList }
     * 
     */
    public PrecursorList createPrecursorList() {
        return new PrecursorList();
    }

    /**
     * Create an instance of {@link StringDataArray }
     * 
     */
    public StringDataArray createStringDataArray() {
        return new StringDataArray();
    }

    /**
     * Create an instance of {@link SpectrumHeader }
     * 
     */
    public SpectrumHeader createSpectrumHeader() {
        return new SpectrumHeader();
    }

    /**
     * Create an instance of {@link SourceFile }
     * 
     */
    public SourceFile createSourceFile() {
        return new SourceFile();
    }

    /**
     * Create an instance of {@link FileChecksum }
     * 
     */
    public FileChecksum createFileChecksum() {
        return new FileChecksum();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sashimi.sourceforge.net/schema_revision/DataXML_0.1", name = "dataXML")
    public JAXBElement<DataXML> createDataXML(DataXML value) {
        return new JAXBElement<DataXML>(_DataXML_QNAME, DataXML.class, null, value);
    }

}
