//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.14 at 04:04:07 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sashimi.sourceforge.net/schema_revision/DataXML_0.1")
package org.proteomecommons.io.dataxml;
