//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.14 at 04:04:07 AM EST 
//


package org.proteomecommons.io.dataxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpectrumHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpectrumHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cvParam" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}CVParam" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="acquisitionList" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}AcquisitionList" minOccurs="0"/>
 *         &lt;element name="precursorList" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}PrecursorList" minOccurs="0"/>
 *         &lt;element name="instrumentSetting" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}InstrumentSetting" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpectrumHeader", propOrder = {
    "cvParam",
    "acquisitionList",
    "precursorList",
    "instrumentSetting"
})
public class SpectrumHeader {

    @XmlElement(required = true)
    protected List<CVParam> cvParam;
    protected AcquisitionList acquisitionList;
    protected PrecursorList precursorList;
    protected InstrumentSetting instrumentSetting;

    /**
     * Gets the value of the cvParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cvParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCvParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CVParam }
     * 
     * 
     */
    public List<CVParam> getCvParam() {
        if (cvParam == null) {
            cvParam = new ArrayList<CVParam>();
        }
        return this.cvParam;
    }

    /**
     * Gets the value of the acquisitionList property.
     * 
     * @return
     *     possible object is
     *     {@link AcquisitionList }
     *     
     */
    public AcquisitionList getAcquisitionList() {
        return acquisitionList;
    }

    /**
     * Sets the value of the acquisitionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcquisitionList }
     *     
     */
    public void setAcquisitionList(AcquisitionList value) {
        this.acquisitionList = value;
    }

    /**
     * Gets the value of the precursorList property.
     * 
     * @return
     *     possible object is
     *     {@link PrecursorList }
     *     
     */
    public PrecursorList getPrecursorList() {
        return precursorList;
    }

    /**
     * Sets the value of the precursorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecursorList }
     *     
     */
    public void setPrecursorList(PrecursorList value) {
        this.precursorList = value;
    }

    /**
     * Gets the value of the instrumentSetting property.
     * 
     * @return
     *     possible object is
     *     {@link InstrumentSetting }
     *     
     */
    public InstrumentSetting getInstrumentSetting() {
        return instrumentSetting;
    }

    /**
     * Sets the value of the instrumentSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstrumentSetting }
     *     
     */
    public void setInstrumentSetting(InstrumentSetting value) {
        this.instrumentSetting = value;
    }

}
