//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.14 at 04:04:07 AM EST 
//


package org.proteomecommons.io.dataxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Spectrum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Spectrum">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spectrumHeader" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}SpectrumHeader"/>
 *         &lt;element name="spectrumData" type="{http://sashimi.sourceforge.net/schema_revision/DataXML_0.1}SpectrumData"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scanNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Spectrum", propOrder = {
    "spectrumHeader",
    "spectrumData"
})
public class Spectrum {

    @XmlElement(required = true)
    protected SpectrumHeader spectrumHeader;
    @XmlElement(required = true)
    protected SpectrumData spectrumData;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected Integer scanNumber;

    /**
     * Gets the value of the spectrumHeader property.
     * 
     * @return
     *     possible object is
     *     {@link SpectrumHeader }
     *     
     */
    public SpectrumHeader getSpectrumHeader() {
        return spectrumHeader;
    }

    /**
     * Sets the value of the spectrumHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpectrumHeader }
     *     
     */
    public void setSpectrumHeader(SpectrumHeader value) {
        this.spectrumHeader = value;
    }

    /**
     * Gets the value of the spectrumData property.
     * 
     * @return
     *     possible object is
     *     {@link SpectrumData }
     *     
     */
    public SpectrumData getSpectrumData() {
        return spectrumData;
    }

    /**
     * Sets the value of the spectrumData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpectrumData }
     *     
     */
    public void setSpectrumData(SpectrumData value) {
        this.spectrumData = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the scanNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScanNumber() {
        return scanNumber;
    }

    /**
     * Sets the value of the scanNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScanNumber(Integer value) {
        this.scanNumber = value;
    }

}
